# Generated by Django 4.1.1 on 2022-09-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
